# Generated by Django 5.2 on 2025-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("date", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
