# Generated by Django 5.1.4 on 2025-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(default='memory_images/memory.jpg', upload_to='memory_images/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memory',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memory',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(default='2025-4-17'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(default='Memory'),
        ),
    ]
