# Generated by Django 5.1.4 on 2025-04-17 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_memory_image_memory_latitude_memory_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='visibility',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='memory',
            name='business_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(),
        ),
    ]
