# Generated by Django 5.1.5 on 2025-04-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_rename_visibility_memory_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
