# Generated by Django 5.1.5 on 2025-04-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memory_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='address',
        ),
    ]
